### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 20000
}
### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
"transactionId": "fa848251aae14e5ea864d8bea3c80bad",
"accountNumber": "1000000002",
"amount": 20000
}

### query transcation
GET http://localhost:8080/transaction/56935896e2d84ad69c9fd5246f0121d6